# Generated by Django 4.2.3 on 2023-11-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangilikuzapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='e_mail',
            new_name='elektron_pochta',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='sarlavha',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='xabar',
        ),
    ]
